name: Markdown Lint
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [main]
jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          command: config
          globs: |
            .github/.markdownlint.json
            **/*.md
